/**
 * AL JAMAAL OFFICIAL — Product Catalog
 *
 * HOW TO EDIT PRODUCTS:
 *   name        — product name shown on site
 *   category    — "Men", "Women", "Kids", or "Home"
 *   price       — price in Rands (number only, no R symbol) — UPDATE with real prices
 *   image       — path to image file once you have photos, e.g. "images/burnoose.jpg"
 *   badge       — small label on the card: "New", "Sale", "Limited", or "" for none
 *   description — short product description shown on card
 */

const products = [

  // ── TESTING ONLY — remove before handoff ───────────────
  {
    id: 99,
    name: "Testing Item",
    category: "Men",
    price: 17,
    sizeLabels: ['Length', 'Chest'],
    sizes: [
      { size: '50 Small',  price: 17 },
      { size: '50 Medium', price: 17 },
      { size: '50 Large',  price: 17 },
      { size: '52 Small',  price: 17 },
      { size: '52 Medium', price: 17 },
      { size: '52 Large',  price: 17 },
    ],
    colors: ['Black', 'White', 'Red'],
    stock: {
      '50 Small':  { 'Black': 5, 'White': 0, 'Red': 1 },
      '50 Medium': { 'Black': 3, 'White': 6, 'Red': 0 },
      '50 Large':  { 'Black': 0, 'White': 2, 'Red': 5 },
      '52 Small':  { 'Black': 2, 'White': 0, 'Red': 3 },
      '52 Medium': { 'Black': 0, 'White': 3, 'Red': 2 },
      '52 Large':  { 'Black': 4, 'White': 1, 'Red': 0 },
    },
    image: "images/BrandIcon.png",
    images: ["images/BrandIcon.png"],
    badge: "Testing",
    description: "This is an internal testing item used to verify payments and site functionality. R1–R3 only. Please do not purchase."
  },

  // ── MEN ────────────────────────────────────────────────
  {
    id: 1,
    name: "Original Burnoose",
    category: "Men",
    price: 850,
    sizeLabels: ['Length', 'Chest'],
    sizes: [
      { size: '50 Small',          price: 990  },
      { size: '50 Medium',         price: 990  },
      { size: '50 Large',          price: 990  },
      { size: '50 X-Large',        price: 990  },
      { size: '50 2X-Large',       price: 1150 },
      { size: '52 Small',          price: 990  },
      { size: '52 Medium',         price: 990  },
      { size: '52 Large',          price: 990  },
      { size: '52 X-Large',        price: 990  },
      { size: '52 2X-Large',       price: 1150 },
      { size: '54 Small',          price: 990  },
      { size: '54 Medium',         price: 990  },
      { size: '54 Large',          price: 990  },
      { size: '54 X-Large',        price: 990  },
      { size: '54 2X-Large',       price: 1150 },
      { size: '56 Small',          price: 990  },
      { size: '56 Medium',         price: 990  },
      { size: '56 Large',          price: 990  },
      { size: '56 X-Large',        price: 990  },
      { size: '56 2X-Large',       price: 1150 },
      { size: '58 Small',          price: 990  },
      { size: '58 Medium',         price: 990  },
      { size: '58 Large',          price: 990  },
      { size: '58 X-Large',        price: 990  },
      { size: '58 2X-Large',       price: 1150 },
      { size: '60 Small',          price: 1075 },
      { size: '60 Medium',         price: 1075 },
      { size: '60 Large',          price: 1075 },
      { size: '60 X-Large',        price: 1075 },
      { size: '60 2X-Large',       price: 1150 },
      { size: '62 Small',          price: 1075 },
      { size: '62 Medium',         price: 1075 },
      { size: '62 Large',          price: 1075 },
      { size: '62 X-Large',        price: 1075 },
      { size: '62 2X-Large',       price: 1150 }
    ],
    colors: ['Black', 'Camel', 'Light Grey', 'Navy Blue'],
    image: "images/OBurnooseM.png",
    images: ["images/OBurnooseM.png", "images/OBurnooseS1.png", "images/OBurnooseS2.jpg", "images/OBurnooseS3.jpg", "images/OBurnooseS4.png", "images/OBurnooseS5.jpg"],
    badge: "",
    description: "Rooted in quality and born from a love of modest fashion, the Al-Jamaal Original Fleece Burnoose is our most-loved design. Thick and cosy with a longer, more generous cut than a standard jubba, with a front zip and generous pockets, it's built to handle South Africa's coldest winters in style. Available in Black, Camel, Light Grey, and Navy Blue."
  },
  {
    id: 2,
    name: "Lightweight Burnoose",
    category: "Men",
    price: 1000,
    sizeLabels: ['Length', 'Chest'],
    sizes: [
      { size: '48 Small',          price: 1000 },
      { size: '48 Medium',         price: 1250 },
      { size: '48 Large',          price: 1250 },
      { size: '48 X-Large',        price: 1250 },
      { size: '48 2X-Large',       price: 1350 },
      { size: '50 Small',          price: 1250 },
      { size: '50 Medium',         price: 1250 },
      { size: '50 Large',          price: 1250 },
      { size: '50 X-Large',        price: 1250 },
      { size: '50 2X-Large',       price: 1250 },
      { size: '52 Small',          price: 1250 },
      { size: '52 Medium',         price: 1250 },
      { size: '52 Large',          price: 1250 },
      { size: '52 X-Large',        price: 1250 },
      { size: '52 2X-Large',       price: 1250 },
      { size: '54 Small',          price: 1250 },
      { size: '54 Medium',         price: 1250 },
      { size: '54 Large',          price: 1250 },
      { size: '54 X-Large',        price: 1250 },
      { size: '54 2X-Large',       price: 1250 },
      { size: '56 Small',          price: 1250 },
      { size: '56 Medium',         price: 1250 },
      { size: '56 Large',          price: 1250 },
      { size: '56 X-Large',        price: 1250 },
      { size: '56 2X-Large',       price: 1250 },
      { size: '58 Small',          price: 1250 },
      { size: '58 Medium',         price: 1250 },
      { size: '58 Large',          price: 1250 },
      { size: '58 X-Large',        price: 1250 },
      { size: '58 2X-Large',       price: 1250 },
      { size: '60 Small',          price: 1300 },
      { size: '60 Medium',         price: 1300 },
      { size: '60 Large',          price: 1300 },
      { size: '60 X-Large',        price: 1300 },
      { size: '60 2X-Large',       price: 1400 },
      { size: '62 Small',          price: 1300 },
      { size: '62 Medium',         price: 1300 },
      { size: '62 Large',          price: 1300 },
      { size: '62 X-Large',        price: 1300 },
      { size: '62 2X-Large',       price: 1400 }
    ],
    image: "images/LBurnooseM.jpg",
    images: ["images/LBurnooseM.jpg", "images/LBurnooseS1.jpg", "images/LBurnooseS2.png", "images/LBurnooseS3.png", "images/LBurnooseS4.png"],
    badge: "",
    description: "The Al-Jamaal Khareef Collection. A wind and water resistant lightweight burnoose with a smooth, structured finish, full-length zip, drawstring hood, and deep pockets. Each side pocket features a built-in interior zipper, giving you direct access to the pockets of whatever you're wearing underneath, no need to take your hands out. Available in a wide range of colours for the whole family."
  },
  {
    id: 3,
    name: "Al-Jamaal ¾ Shorts",
    category: "Men",
    price: 300,
    sizeLabels: ['Size'],
    sizes: [
      { size: 'Medium (28" – fits up to 32")',       price: 300 },
      { size: 'Large (30" – fits up to 34")',         price: 300 },
      { size: 'X-Large (32" – fits up to 36")',       price: 300 },
      { size: '2X-Large (34" – fits up to 38")',      price: 300 },
      { size: '3X-Large (35/36" – fits up to 40")',   price: 315 },
      { size: '4X-Large (37/38" – fits up to 42")',   price: 315 },
      { size: '5X-Large (39/40" – fits up to 44")',   price: 315 },
      { size: '6X-Large (41/42" – fits up to 46")',   price: 315 }
    ],
    image: "images/3:4ShortsM.jpg",
    images: ["images/3:4ShortsM.jpg", "images/3:4 shorts video.mp4", "images/3:4ShortsS1.jpg", "images/3:4ShortsS2.png", "images/3:4ShortsS3.png", "images/3:4ShortsS4.jpg", "images/3:4ShortsS5.jpg", "images/3:4ShortsS6.jpg"],
    badge: "",
    description: "The Al-Jamaal ¾ Over-the-Knee Shorts are built for every occasion. Crafted from a cooling, quick-dry fabric with an elasticated waistband, drawstring, and zipped pockets, they're as practical as they are comfortable. Over-the-knee for modest coverage, relaxed enough for daily wear, and durable enough for swimming, sport, travel, and everything in between. Available in 9 colours including Teal, Navy, Charcoal, Royal Blue, and more. Locally manufactured in South Africa."
  },
  {
    id: 4,
    name: "Fleece Jacket",
    category: "Men",
    price: 800,
    image: "images/FJacketM.png",
    images: ["images/FJacketM.png", "images/FJacketS1.png", "images/FJacketS2.png", "images/FJacketS3.png"],
    badge: "",
    description: "Don't freeze in the cold. The Al-Jamaal Fleece Jacket combines the warmth of our bestselling burnoose in a shorter, more versatile silhouette. Featuring a striking two-tone colour block design, thick fleece fabric, drawstring hood, full front zip, and zipped pockets, it's a winter essential that's as stylish as it is functional. Available in selected colours and sizes."
  },
  {
    id: 17,
    name: "Lightweight Jacket",
    category: "Men",
    price: 800,
    image: "images/Lightweight-JacketM.png",
    images: ["images/Lightweight-JacketM.png"],
    badge: "",
    description: "Stay comfortable without the bulk. The Al-Jamaal Lightweight Jacket delivers warmth and versatility in a shorter, more adaptable silhouette. Featuring a striking two-tone colour block design, lightweight insulated fabric, a drawstring hood, full front zip, and zipped pockets, it's an essential layer that balances style and function. Available in selected colours and sizes."
  },

  // ── WOMEN ──────────────────────────────────────────────
  {
    id: 6,
    name: "Khareef Ladies Long Jacket",
    category: "Women",
    price: 1250,
    sizeLabels: ['Length', 'Chest'],
    sizes: [
      { size: '50 Small',    price: 1250 },
      { size: '50 Medium',   price: 1250 },
      { size: '50 Large',    price: 1250 },
      { size: '50 X-Large',  price: 1250 },
      { size: '52 Small',    price: 1250 },
      { size: '52 Medium',   price: 1250 },
      { size: '52 Large',    price: 1250 },
      { size: '52 X-Large',  price: 1250 },
      { size: '54 Small',    price: 1250 },
      { size: '54 Medium',   price: 1250 },
      { size: '54 Large',    price: 1250 },
      { size: '54 X-Large',  price: 1250 },
      { size: '56 Small',    price: 1250 },
      { size: '56 Medium',   price: 1250 },
      { size: '56 Large',    price: 1250 },
      { size: '56 X-Large',  price: 1250 },
      { size: '56 3X-Large', price: 1500 },
      { size: '58 Small',    price: 1250 },
      { size: '58 Medium',   price: 1250 },
      { size: '58 Large',    price: 1250 },
      { size: '58 X-Large',  price: 1250 },
      { size: '58 3X-Large', price: 1500 },
      { size: '60 Small',    price: 1300 },
      { size: '60 Medium',   price: 1300 },
      { size: '60 Large',    price: 1300 },
      { size: '60 X-Large',  price: 1300 },
      { size: '60 3X-Large', price: 1500 }
    ],
    colors: ['Black', 'Dark Beige', 'Dark Grey', 'Light Beige', 'Navy Blue', 'Olive Green'],
    stock: {
      '50 Small':    { 'Black': 2 },
      '50 Medium':   { 'Black': 1 },
      '50 Large':    { 'Dark Grey': 1 },
      '52 Small':    { 'Black': 3 },
      '52 Medium':   { 'Dark Grey': 2 },
      '54 Small':    { 'Dark Grey': 1, 'Black': 1 },
      '54 Medium':   { 'Black': 1, 'Light Beige': 2, 'Dark Grey': 1 },
      '54 Large':    { 'Black': 3, 'Navy Blue': 1 },
      '54 X-Large':  { 'Olive Green': 1, 'Dark Grey': 1 },
      '56 Large':    { 'Navy Blue': 1, 'Olive Green': 1 },
      '56 3X-Large': { 'Black': 1 },
      '58 Small':    { 'Black': 1, 'Dark Beige': 2 },
      '58 X-Large':  { 'Dark Grey': 1, 'Black': 1 },
      '58 3X-Large': { 'Dark Grey': 1 },
      '60 Large':    { 'Black': 2 },
      '60 X-Large':  { 'Black': 3 },
      '60 3X-Large': { 'Black': 2 }
    },
    image: "images/KLLJ.jpg",
    images: ["images/KLLJ.jpg"],
    badge: "",
    description: "The Khareef Ladies Long Jacket by Al-Jamaal. A sleek, long-line outer layer crafted from smooth, wind and water resistant fabric. Modest in coverage, refined in style, and tailored to move with you. Featuring a hooded design and side pockets, it's the versatile winter essential every wardrobe needs."
  },
  {
    id: 5,
    name: "Al-Jamaal Burqa",
    category: "Women",
    price: 850,
    image: "images/BurqaM.png",
    images: ["images/BurqaM.png", "images/BurqaS1.png", "images/BurqaS2.jpg", "images/BurqaS3.png", "images/BurqaS4.png", "images/BurqaS5.png", "images/BurqaS6.png", "images/BurqaS7.png", "images/BurqaS8.png"],
    badge: "",
    description: "The Al-Jamaal Burqa is designed for the woman who values modesty without compromising on style. Made from the finest non-see-through fabric with a flowy, comfortable fit, it's as elegant as it is practical. Available in an extensive range of shades from soft pastels to rich bold tones. Custom full-length options with or without sleeves available on request."
  },
  {
    id: 7,
    name: "Farasha Daily Wear Khimaar",
    category: "Women",
    price: 0,
    image: "images/FKhimaarM.jpg",
    images: ["images/FKhimaarM.jpg", "images/FKhimaarS1.png", "images/FKhimaarS2.png", "images/FKhimaarS3.png"],
    badge: "",
    description: "The Al-Jamaal Farasha Dailywear Khimaar is a luxurious mid-length cover-up that embodies grace and modesty. Crafted from a lightweight, flowing fabric, it drapes elegantly over the shoulders with a fully covered front and a slightly longer flowing back. The open front is secured with a discreet press stud, and the elasticated headband ensures a secure, comfortable fit. Designed with nursing in mind, it is both practical and refined. Compatible with a niqab. Locally manufactured in South Africa."
  },
  {
    id: 8,
    name: "Aaroosa Bridal Khimaar",
    category: "Women",
    price: 0,
    image: "images/ABKhimaar.jpg",
    images: ["images/ABKhimaar.jpg"],
    badge: "Special",
    description: "The Al-Jamaal Aaroosa Bridal Khimaar is an elegant cover-up designed for the bride who values grace and modesty on her most special day. Featuring a flowing cape silhouette, it drapes beautifully over your wedding ensemble, adding refined coverage without taking away from your look. The closed top ensures full concealment while the front slit allows for effortless movement and fluid elegance. Ethereal in appearance and meaningful in purpose, it also makes a truly cherished bridal gift."
  },
  {
    id: 20,
    name: "Ladies Fleece Burnoose",
    category: "Women",
    price: 990,
    sizeLabels: ['Length', 'Chest'],
    sizes: [
      { size: '50 Small',    price: 990  },
      { size: '50 Medium',   price: 990  },
      { size: '50 Large',    price: 990  },
      { size: '50 X-Large',  price: 990  },
      { size: '52 Small',    price: 990  },
      { size: '52 Medium',   price: 990  },
      { size: '52 Large',    price: 990  },
      { size: '52 X-Large',  price: 990  },
      { size: '54 Small',    price: 990  },
      { size: '54 Medium',   price: 990  },
      { size: '54 Large',    price: 990  },
      { size: '54 X-Large',  price: 990  },
      { size: '54 2X-Large', price: 1150 },
      { size: '56 Small',    price: 990  },
      { size: '56 Medium',   price: 990  },
      { size: '56 Large',    price: 990  },
      { size: '56 X-Large',  price: 990  },
      { size: '56 2X-Large', price: 1150 },
      { size: '56 3X-Large', price: 1200 },
      { size: '58 Small',    price: 990  },
      { size: '58 Medium',   price: 990  },
      { size: '58 Large',    price: 990  },
      { size: '58 X-Large',  price: 990  },
      { size: '58 2X-Large', price: 1150 },
      { size: '60 Small',    price: 1075 },
      { size: '60 Medium',   price: 1075 },
      { size: '60 Large',    price: 1075 },
      { size: '60 X-Large',  price: 1075 }
    ],
    colors: ['Beige', 'Black', 'Camel', 'Dark Green', 'Dark Grey', 'Dark Pink', 'Light Blue', 'Light Grey', 'Light Pink', 'Maroon', 'Navy Blue'],
    stock: {
      '50 Small':    { 'Light Blue': 2, 'Navy Blue': 2, 'Dark Grey': 1, 'Dark Pink': 1 },
      '50 Medium':   { 'Dark Grey': 1, 'Navy Blue': 2, 'Camel': 2, 'Maroon': 1 },
      '50 Large':    { 'Light Grey': 1 },
      '50 X-Large':  { 'Maroon': 1 },
      '52 Small':    { 'Dark Pink': 1, 'Dark Green': 1, 'Beige': 4 },
      '52 Medium':   { 'Navy Blue': 1, 'Camel': 2 },
      '52 Large':    { 'Camel': 2, 'Black': 1, 'Maroon': 1 },
      '52 X-Large':  { 'Black': 1, 'Camel': 2 },
      '54 Small':    { 'Black': 1, 'Beige': 5 },
      '54 Medium':   { 'Navy Blue': 1, 'Black': 2 },
      '54 Large':    { 'Camel': 1, 'Light Grey': 1 },
      '54 X-Large':  { 'Black': 1, 'Camel': 1, 'Light Grey': 1, 'Dark Grey': 1 },
      '54 2X-Large': { 'Black': 1, 'Light Grey': 1 },
      '56 Small':    { 'Black': 4, 'Light Grey': 1, 'Dark Grey': 2 },
      '56 Medium':   { 'Black': 1, 'Dark Grey': 2, 'Light Grey': 2, 'Camel': 1, 'Dark Pink': 1, 'Navy Blue': 2 },
      '56 Large':    { 'Light Pink': 1, 'Black': 3 },
      '56 X-Large':  { 'Dark Grey': 1, 'Light Grey': 2, 'Camel': 1, 'Beige': 1 },
      '56 2X-Large': { 'Black': 2, 'Light Grey': 2 },
      '56 3X-Large': { 'Black': 1 },
      '58 Small':    { 'Black': 2 },
      '58 Medium':   { 'Camel': 1, 'Black': 2 },
      '58 Large':    { 'Light Grey': 1 },
      '58 X-Large':  { 'Light Grey': 2, 'Camel': 2 },
      '58 2X-Large': { 'Black': 2 },
      '60 Small':    { 'Black': 2 },
      '60 Medium':   { 'Black': 2, 'Camel': 1 },
      '60 Large':    { 'Dark Grey': 2, 'Navy Blue': 2 },
      '60 X-Large':  { 'Black': 1, 'Dark Grey': 2 }
    },
    image: "",
    images: [],
    badge: "New",
    description: "The Al-Jamaal Ladies Fleece Burnoose — the warmth of our bestselling Original Burnoose in a design made for her. Crafted from the same thick, premium fleece with a full front zip, it features a tighter, more tailored fit. Available in a range of colours. Need a bigger size? Contact us and we'll sort you out."
  },

  // ── KIDS ───────────────────────────────────────────────
  {
    id: 11,
    name: "Kids Shorts",
    category: "Kids",
    price: 180,
    sizeLabels: ['Size'],
    sizes: [
      { size: '1–2 Years (11")',    price: 180 },
      { size: '2–3 Years',          price: 180 },
      { size: '3–4 Years (16")',    price: 180 },
      { size: '4–5 Years',          price: 180 },
      { size: '5–6 Years (18.5")',  price: 255 },
      { size: '6–7 Years (22")',    price: 255 },
      { size: '7–8 Years (25")',    price: 255 },
      { size: '9–10 Years (26.5")', price: 255 },
      { size: '11–12 Years (28")',  price: 265 },
      { size: '13–14 Years (29.5")',price: 265 }
    ],
    image: "images/KShortsM.jpg",
    images: ["images/KShortsM.jpg", "images/KShortsS1.jpg", "images/KShortsS2.jpg", "images/KShortsS3.jpg", "images/KShortsS4.jpg"],
    badge: "",
    description: "Introducing the Al-Jamaal Mini Me collection. Over-the-knee shorts designed specifically for the little ones. Built from a cool cotton fabric, they keep kids comfortable, covered, and ready for anything. Whether it's a day at the beach, the park, or just playing outside, these shorts are made to move. Available in a range of fun colours including Navy, Blue, Sage, Green, Camel, Black, White, and more."
  },
  {
    id: 10,
    name: "Toddlers Burnoose",
    category: "Kids",
    price: 425,
    sizeLabels: ['Length'],
    sizes: [
      { size: '18', price: 425 },
      { size: '20', price: 425 },
      { size: '22', price: 425 },
      { size: '24', price: 475 },
      { size: '26', price: 475 },
      { size: '28', price: 475 }
    ],
    colors: ['Beige', 'Camel', 'Dark Grey', 'Dark Pink', 'Light Blue', 'Light Grey', 'Light Pink', 'Maroon', 'Navy Blue'],
    stock: {
      '18': {},
      '20': { 'Beige': 2, 'Light Grey': 2, 'Navy Blue': 2, 'Light Blue': 2, 'Camel': 1, 'Dark Pink': 1, 'Light Pink': 1 },
      '22': { 'Dark Grey': 2, 'Beige': 3, 'Light Grey': 2, 'Light Blue': 1 },
      '24': { 'Light Grey': 1 },
      '26': { 'Navy Blue': 1, 'Light Grey': 2, 'Dark Pink': 2 },
      '28': { 'Light Grey': 1, 'Maroon': 1, 'Light Pink': 1, 'Dark Grey': 2, 'Beige': 2, 'Light Blue': 3 }
    },
    image: "images/KBurnooseM.png",
    images: ["images/KBurnooseM.png", "images/KBurnooseS1.png", "images/KBurnooseS2.png", "images/KBurnooseS3.png", "images/KBurnooseS4.png"],
    badge: "",
    description: "Bundle your little ones up in the quality they deserve. The Al-Jamaal Kids Burnoose is crafted from the same premium fleece as our bestselling adult range, tailored to fit from infants all the way up. One zip and they're warm. Available in a wide range of colours including Pink, Blue, Charcoal, Red, Beige, and more."
  },
  {
    id: 18,
    name: "Boys Burnoose",
    category: "Kids",
    price: 525,
    sizeLabels: ['Length'],
    sizes: [
      { size: '30', price: 525 },
      { size: '32', price: 525 },
      { size: '34', price: 525 },
      { size: '36', price: 595 },
      { size: '38', price: 595 },
      { size: '40', price: 675 },
      { size: '42', price: 675 },
      { size: '44', price: 750 },
      { size: '46', price: 750 },
      { size: '48', price: 750 }
    ],
    colors: ['Black', 'Camel', 'Dark Grey', 'Light Blue', 'Light Grey', 'Navy Blue'],
    stock: {
      '30': { 'Dark Grey': 2, 'Camel': 3, 'Navy Blue': 2, 'Black': 2 },
      '32': {},
      '34': { 'Light Grey': 1, 'Light Blue': 2 },
      '36': { 'Navy Blue': 1, 'Dark Grey': 2, 'Black': 2 },
      '38': { 'Light Blue': 1, 'Navy Blue': 2, 'Black': 2 },
      '40': { 'Dark Grey': 1, 'Light Blue': 1, 'Navy Blue': 2 },
      '42': {},
      '44': { 'Navy Blue': 1, 'Light Blue': 1, 'Black': 3 },
      '46': { 'Black': 6, 'Navy Blue': 3, 'Dark Grey': 2 },
      '48': { 'Camel': 1, 'Light Grey': 1, 'Navy Blue': 1, 'Black': 5 }
    },
    image: "images/BBurnooseM.png",
    images: ["images/BBurnooseM.png", "images/BBurnooseS1.jpg"],
    badge: "",
    description: "Bundle your little ones up in the quality they deserve. The Al-Jamaal Boys Burnoose is crafted from the same premium fleece as our bestselling adult range, tailored to fit boys from size 30 up to 48. One zip and they're warm."
  },
  {
    id: 19,
    name: "Girls Burnoose",
    category: "Kids",
    price: 525,
    sizeLabels: ['Length'],
    sizes: [
      { size: '30', price: 525 },
      { size: '32', price: 525 },
      { size: '34', price: 525 },
      { size: '36', price: 595 },
      { size: '38', price: 595 },
      { size: '40', price: 675 },
      { size: '42', price: 675 },
      { size: '44', price: 750 },
      { size: '46', price: 750 },
      { size: '48', price: 750 }
    ],
    colors: ['Beige', 'Black', 'Camel', 'Dark Grey', 'Dark Pink', 'Light Blue', 'Light Grey', 'Light Pink', 'Maroon', 'Navy Blue'],
    stock: {
      '30': { 'Light Pink': 1, 'Camel': 1, 'Dark Grey': 2, 'Black': 3, 'Light Blue': 3 },
      '32': { 'Light Pink': 1, 'Maroon': 2, 'Black': 2, 'Dark Grey': 2, 'Camel': 3 },
      '34': { 'Maroon': 1, 'Black': 1, 'Light Pink': 2, 'Camel': 2 },
      '36': { 'Light Pink': 2, 'Light Grey': 1, 'Beige': 1, 'Light Blue': 1, 'Black': 1, 'Camel': 3, 'Dark Grey': 5 },
      '38': { 'Maroon': 1, 'Black': 1, 'Beige': 2, 'Dark Grey': 2, 'Light Grey': 2, 'Light Blue': 2, 'Camel': 4, 'Dark Pink': 2 },
      '40': { 'Dark Grey': 5, 'Camel': 5, 'Light Blue': 2, 'Dark Pink': 1, 'Black': 2 },
      '42': { 'Black': 1, 'Dark Grey': 3, 'Beige': 2 },
      '44': { 'Camel': 5, 'Beige': 2, 'Navy Blue': 2, 'Dark Grey': 2, 'Black': 2 },
      '46': { 'Camel': 5, 'Navy Blue': 2, 'Black': 4, 'Dark Grey': 2, 'Dark Pink': 1, 'Light Pink': 1 },
      '48': { 'Beige': 1, 'Light Blue': 1, 'Camel': 1, 'Dark Grey': 5, 'Navy Blue': 2 }
    },
    image: "",
    images: [],
    badge: "",
    description: "Bundle your little ones up in the quality they deserve. The Al-Jamaal Girls Burnoose is crafted from the same premium fleece as our bestselling adult range, tailored to fit girls from size 30 up to 48. One zip and they're warm."
  },
  {
    id: 12,
    name: "Mora Sherpa Baby Blanket",
    category: "Kids",
    price: 320,
    image: "images/MsbbM.png",
    images: ["images/MsbbM.png", "images/MsbbS1.png", "images/MsbbS2.png", "images/MsbbS3.png", "images/MsbbS4.jpg", "images/MsbbS5.jpg"],
    badge: "",
    description: "Wrap your baby in the warmth they deserve. The Mora Sherpa Baby Blanket is crafted from a super soft, high-quality sherpa fabric with a beautiful 3D embossed print finish. Its high air circulation keeps your little one warm without the weight of heavy blankets perfect for the crib, the stroller, or cuddles at home. Available in a range of colours and comes beautifully packaged, making it an ideal gift for any new parent."
  },

  {
    id: 21,
    name: "Boys Khareef Soft Shell",
    category: "Kids",
    price: 625,
    sizeLabels: ['Length'],
    sizes: [
      { size: '30', price: 625 },
      { size: '32', price: 625 },
      { size: '34', price: 625 },
      { size: '36', price: 695 },
      { size: '38', price: 695 },
      { size: '40', price: 775 },
      { size: '42', price: 775 },
      { size: '44', price: 850 },
      { size: '46', price: 850 },
      { size: '48', price: 850 }
    ],
    colors: ['Black', 'Dark Grey', 'Light Grey', 'Navy Blue', 'Olive Green', 'Sniper Beige'],
    stock: {
      '30': { 'Black': 1, 'Dark Grey': 1 },
      '32': { 'Black': 3, 'Dark Grey': 2 },
      '34': { 'Black': 2, 'Navy Blue': 2, 'Dark Grey': 5 },
      '36': { 'Black': 1, 'Dark Grey': 1 },
      '38': { 'Olive Green': 1, 'Black': 2, 'Dark Grey': 4 },
      '40': { 'Light Grey': 1, 'Navy Blue': 1 },
      '42': { 'Light Grey': 1, 'Olive Green': 2, 'Dark Grey': 3 },
      '44': { 'Sniper Beige': 1, 'Dark Grey': 2, 'Black': 1 },
      '46': { 'Dark Grey': 1, 'Light Grey': 2, 'Sniper Beige': 2 },
      '48': { 'Sniper Beige': 2 }
    },
    image: "",
    images: [],
    badge: "New",
    description: "The Al-Jamaal Boys Khareef Soft Shell. Wind and water resistant lightweight coverage in the same style as our bestselling adult Khareef collection. Full-length zip, drawstring hood, and deep pockets. Available in sizes 30 to 48."
  },
  {
    id: 22,
    name: "Girls Khareef Soft Shell",
    category: "Kids",
    price: 625,
    sizeLabels: ['Length'],
    sizes: [
      { size: '30', price: 625 },
      { size: '32', price: 625 },
      { size: '34', price: 625 },
      { size: '36', price: 695 },
      { size: '38', price: 695 },
      { size: '40', price: 775 },
      { size: '42', price: 775 },
      { size: '44', price: 850 },
      { size: '46', price: 850 },
      { size: '48', price: 850 }
    ],
    colors: ['Black', 'Dark Beige', 'Dark Grey'],
    stock: {
      '32': { 'Dark Grey': 1 },
      '34': { 'Black': 1 },
      '38': { 'Dark Beige': 1 },
      '40': { 'Dark Beige': 1 },
      '42': { 'Dark Beige': 1 },
      '46': { 'Dark Grey': 2, 'Black': 4 },
      '48': { 'Black': 1 }
    },
    image: "",
    images: [],
    badge: "New",
    description: "The Al-Jamaal Girls Khareef Soft Shell. Wind and water resistant lightweight coverage in the same style as our bestselling adult Khareef collection. Full-length zip, drawstring hood, and deep pockets. Available in sizes 30 to 48."
  },

  // ── HOME ───────────────────────────────────────────────
  {
    id: 13,
    name: "Tablecloth",
    category: "Home & Gifts",
    price: 780,
    image: "images/TableM.png",
    images: ["images/TableM.png", "images/TableS1.png", "images/TableS2.png", "images/TableS3.png", "images/TableS4.png", "images/TableS5.png", "images/TableS6.png", "images/TableS7.png", "images/TableS8.png", "images/TableS9.png", "images/TableS10.png", "images/TableS11.png"],
    badge: "Sold Out",
    description: "Dine in style with the Al-Jamaal Tablecloth Collection. Each piece is made from thick, high-quality fabric from richly textured velvets and stunning layered lace to vibrant florals and contemporary prints. Whether you're setting a table for Eid, a family gathering, or a Friday brunch, there's a print and size to suit every occasion. Available in multiple sizes and a wide variety of prints. Makes a stunning gift."
  },
  {
    id: 15,
    name: "The Great Mosque of Mecca",
    category: "Home & Gifts",
    price: 2100,
    stock: 1,
    image: "images/TGMosqueM.jpg",
    images: ["images/TGMosqueM.jpg", "images/TGMosqueS1.jpg", "images/TGMosqueS2.jpg", "images/TGMosqueS3.jpg", "images/TGMosqueS4.jpg"],
    badge: "",
    description: "Experience the beauty and grandeur of the Great Mosque of Mecca with this stunning 2291 pieces building block set from Wange. Build an exact replica and marvel at the intricate details of this iconic structure. Perfect for both display and play, this set is a must-have for any architecture enthusiast or fan of the historic landmark.<br><br>Set Includes: 2291 Pieces<br>Built Dimensions: 62.2 x 43.4 x 22.1 cm / 24.49 x 17.09 x 8.70 in (L x W x H)<br>Age Recommendation: 6+ Years Old"
  },
  {
    id: 16,
    name: "Wange Mosque Kaaba of Mecca",
    category: "Home & Gifts",
    price: 850,
    stock: 1,
    image: "images/Mosque-KaabaM.jpg",
    images: ["images/Mosque-KaabaM.jpg", "images/Mosque-KaabaS1.jpg", "images/Mosque-KaabaS2.jpg"],
    badge: "",
    description: "This Mecca Grand Mosque Kaaba building block set beautifully captures the iconic architecture of Islamic culture, making it more than just a toy—it's a meaningful symbol of faith, tradition, and blessing. Designed to balance education and entertainment, it encourages children to develop hand-eye coordination, spatial awareness, and creativity while learning about the history and cultural significance of the Great Mosque of Mecca. Perfect as a thoughtful gift for Eid al-Fitr, it promotes family bonding by inviting parents and children to build together, creating shared moments of discovery and connection. Crafted from safe, environmentally friendly materials with smooth edges and durable design, it ensures both safety and long-lasting enjoyment. With hundreds of pieces and detailed instructions, this set offers a rich, engaging building experience that nurtures patience, logical thinking, and a deeper appreciation for culture through play.<br><br>Set Includes: 446 Pieces<br>Built Dimensions: 24 x 24 x 14.1 cm / 9.45 x 9.45 x 5.55 in (L x W x H)<br>Age Recommendation: 6+ Years Old"
  }

];
